name: OpenAPI runner (per-endpoint)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "API mode to process (store|admin)"
        required: true
        default: "store"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-24.04
    env:
      APP_ENV: prod
      APP_URL: http://localhost:8000
      DATABASE_HOST: "127.0.0.1"
    steps:
      - name: Setup Shopware
        uses: shopware/setup-shopware@main
        with:
          install: true
          shopware-version: ${{ github.ref }}
          shopware-repository: ${{ github.repository }}

      - name: Cache npm packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # 4
        with:
          path: ${{ github.workspace }}/var/cache/npm
          key: change-me-on-shopware-api-gen-update

      - name: Prepare schema tools
        env:
          NPM_CONFIG_PREFIX: ${{ github.workspace }}/var/cache/npm
        run: |
          echo "PATH=${{ env.NPM_CONFIG_PREFIX }}/bin:$PATH" >> $GITHUB_ENV
          curl localhost:8000/
          npm i -g @redocly/cli@1.32.1 @shopware/api-gen
          export STOREFRONT_ID=$(bin/console sales-channel:list --output json | jq -r '.[] | select(.name == "Storefront") | .id')
          export OPENAPI_ACCESS_KEY=$(mysql -u root -h 127.0.0.1 shopware -se "SELECT access_key FROM sales_channel WHERE id = UNHEX(\"${STOREFRONT_ID}\")";)
          echo -e "OPENAPI_JSON_URL=http://localhost:8000\nSHOPWARE_ADMIN_USERNAME=admin\nSHOPWARE_ADMIN_PASSWORD=shopware\nOPENAPI_ACCESS_KEY=${OPENAPI_ACCESS_KEY}" > .env
          cat .env

      - name: Run OpenAPI runner (one endpoint)
        env:
          MODE: ${{ inputs.mode }}
          REMOTE: origin
        run: |
          node openapi/scripts/runner.js "$MODE" "$REMOTE"


